version: "3.8"
services:
  apache:
    build: ./infra/apache
    volumes:
      - ./laravel:/work

  # nginx:
    # nginxの公式イメージ（偶数が安定バージョンらしい）
    # image: nginx:1.18-alpine
    # ports:
    #   - 10080:80
    # volumes:
    #   - ./backend:/work
    #   - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # working_dir: /work

  # 公式イメージをそのまま利用
  # mysql:
  #   build: ./infra/mysql
  #   volumes:
  #     - db-store:/var/lib/mysql

# volumes:
#   db-store:
